# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefas.Projeto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefas.Usuario')),
            ],
        ),
    ]
