# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_projetousuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('dataEHoraDeInicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dataEHoraDeInicio')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefas.Projeto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefas.Usuario')),
            ],
        ),
    ]
